apiVersion: apps/v1
kind: Deployment
metadata:
  name: signet-frontend-dev
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signet-frontend-dev
  template:
    metadata:
      labels:
        app: signet-frontend-dev
    spec:
      containers:
        - name: frontend
          image: imageName
